### PR TITLE
Initial translation

### PR DESCRIPTION
**Pull request by bellentani**
Below are the first pages translated into PT-BR (Brazilian Portuguese, there is a noticeable difference between the "official" Portuguese).

I inserted an observation in Intro about translated terms, because it doesn't make sense to keep only full translations for terms that are used in the original Program and also common to languages like CSS and HTML.

The observation says:

"Note of translation for Brazilian Portuguese: we decided to keep the nomenclatures with the original names of the CSS and Figma properties for the tokens, categories and other items related to development. However, we use the translation in columns of tables or in parentheses right after this ocurrencies. The objective of this is to cover all professionals, from those who use the tool in Portuguese to those who prefer the original language (English) - even those who need the original references for code (Example: there is no CSS in Portuguese). "

### CODE REVIEW

**Comment by six7** [comment]
#### 📝Changed routes:


| [**/index.pt-br**](https://figma-tokens-docs-3neku7aen-six7.vercel.app/index.pt-br) | [**…available-tokens.pt-br**](https://figma-tokens-docs-3neku7aen-six7.vercel.app/tokens/available-tokens.pt-br) |
|:-:|:-:|
|<a href="https://figma-tokens-docs-3neku7aen-six7.vercel.app/index.pt-br">Screenshot of /index.pt-br</a><br /><sup><a href="https://images.weserv.nl?url=https://iad.microlink.io/ANwOff7kG8MPXv0U1ICt2tZW9L53xRLLEzFu1grPylvt5wipuMhr3F_-Y5ahdHZYKUnXAEoGHvryXTJWHaKzAw.png">(view full size)</a> |<a href="https://figma-tokens-docs-3neku7aen-six7.vercel.app/tokens/available-tokens.pt-br">Screenshot of /tokens/available-tokens.pt-br</a><br /><sup><a href="https://images.weserv.nl?url=https://iad.microlink.io/7bPdbiMjhpoB5V8UKhdL4ibR3-lw34eyblbNxOghJKpIX5DDfdpQHFuokRcgfVbs1WSPRnQ10Hyz_Axjcsr2Dw.png">(view full size)</a> |







Commit 499d3ba2b99ffcbf2fca3a77122676e6d709fda8 (https://figma-tokens-docs-3neku7aen-six7.vercel.app).

**Comment by six7** [comment]
This is awesome, thank you Poe! I'll have a look at it over the next coming days, I think we'll need to configure the locale file differently according to the [Nextra docs](https://nextra.vercel.app/features/i18n) (`nextra.config.js` and `theme.config.js` need a i18n property with our languages setup).

Again, thank you 👍

**Comment by bellentani** [comment]
> This is awesome, thank you Poe! I'll have a look at it over the next coming days, I think we'll need to configure the locale file differently according to the [Nextra docs](https://nextra.vercel.app/features/i18n) (`nextra.config.js` and `theme.config.js` need a i18n property with our languages setup).
> 
> Again, thank you 👍

;) Yeap! Im with focus and efforts to translate content, but no hurry... when content was done I can help with this Vercel configs.

**Comment by six7** [comment]
> > This is awesome, thank you Poe! I'll have a look at it over the next coming days, I think we'll need to configure the locale file differently according to the [Nextra docs](https://nextra.vercel.app/features/i18n) (`nextra.config.js` and `theme.config.js` need a i18n property with our languages setup).
> > 
> > Again, thank you 👍
> 
> ;) Yeap! Im with focus and efforts to translate content, but no hurry... when content was done I can help with this Vercel configs. 

Don't worry about the config, I can focus on these 🙏

**Comment by bellentani** [comment]
All docs translated. 

Sorry I'm late, but it's there. 1 month later than expected, but 100% done. ;)

If you need help with the config, tell me. See ya!

**Comment by six7** [comment]
Thank you, @bellentani — this is great! And just in time, there was a bug in Nextra preventing me from working on the config which was fixed only 2 days ago 🙏 I'll try to get it into main today. Again, thank you so much for the work you've put into this!

https://github.com/shuding/nextra/issues/127

**Review by six7 — APPROVED** [review]

**Pull request merged**
